### ISSUE TITLE
safe parsing

### ISSUE THREAD

**Issue by capaj** [MaiaVictor/LJSON#1]
have you had any ideas how to do safe parsing? Have you considered somthing like https://github.com/asvd/jailed or https://github.com/gf3/sandbox ?

**Comment by thriqon** [comment]
If you want real parsing instead of safe-executing you can also take a look at [Esprima](http://esprima.org/), it gives you an AST.

**Comment by VictorTaelin** [comment]
I think safe parsing would just be a matter of adding functions and function application to JSON's grammar. Non-bound variables would throw an error, so you still can't call arbitrary code. I would work on something similar to [Caramel](https://github.com/maiavictor/caramel)'s parser (which uses the ReadP library on Haskell's base), but I didn't search for parse combinator libraries on JS yet. I'll give it a look eventually!

**Comment by VictorTaelin** [comment]
Safe parsing added on this new release.
