### ISSUE TITLE
[feature-request] add return value undefined

### ISSUE THREAD

**Issue by Kanti** [MaiaVictor/LJSON#10]
I think it would be better if no return is present the stringify function would return something like this:

``` js
"(v0,v1) => (undefined)"
```

see #8

**Comment by VictorTaelin** [comment]
Seems reasonable, but I don't know how we could implement that.

**Comment by Kanti** [comment]
``` js
"(v0,v1) => (undefined)"

//converts to 
return function (v0, v1) {};//return's a function which return's undefined
```

``` php
//or in PHP
return function ($v0, $v1) {};//return's a function which return's null
```

I'm creating a Pull request

**Comment by VictorTaelin** [comment]
That looks reasonable... we don't have tests yet, did you test it with all the examples and it work fine?

**Comment by Kanti** [comment]
I will test it and than give feedback
