### ISSUE TITLE
Case sensitive systems fail to import

### ISSUE THREAD

**Issue by alvarolorentedev** [MaiaVictor/LJSON#15]
I think there is a typo

```
var parsenhora = require("./parsenhora.js");
```

should be:

```
var parsenhora = require("./Parsenhora.js");
```

operating systems that take care of capital letters will fail to find the dependency. I had this in linux developing an electron app.

if is not something you expected, do you mind i change it and make a PR.

**Comment by VictorTaelin** [comment]
Thanks
