### ISSUE TITLE
ES6 arrow functions instead of anonymous functions?

### ISSUE THREAD

**Issue by blixt** [MaiaVictor/LJSON#4]
It might be nicer and more succinct to use arrow functions in the string representation. Since it's parsed, they can easily be converted back to anonymous functions for older browsers.

Example:

``` javascript
(v0, v1) => "No, it is not the time to use that."
// instead of:
(function(v0,v1){return "No, it is not the time to use that."})
```

**Comment by VictorTaelin** [comment]
I'm not sure how I feel about that. The syntax is obviously much superior, but is it worth not being able to copypaste LJSON expressions in older JS versions? I really don't know.

**Comment by blixt** [comment]
If it helps make a decision, current stable versions of Node.js, Firefox, Chrome, and Edge all [support arrow functions](http://caniuse.com/#search=arrow). For the remaining browsers, transpilers are increasingly common (as evident by the fact that this module is itself uses CommonJS modules so it has to be transpiled to work in browsers), and Babel and Traceur will convert the arrow functions to anonymous functions.

**Comment by ckknight** [comment]
I think that once a real parser is written, rather than relying on `eval`, a decision can be made about final function syntax, as it won't matter which engine supports arrows or does not.

**Comment by VictorTaelin** [comment]
I'm using arrow functions on this new release, but I'm still not decided on the issue. I'd like to hear more opinions.

**Comment by Kanti** [comment]
With the parse function this is not a problem anymore.
